name: App Deployment Pipeline

on:
  workflow_run:
    workflows: ["Terraform Infra Pipeline"]
    types:
      - completed
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: terraform-eks-microservices-ci-cd-eks-cluster
  ECR_REPO_NAME: terraform-eks-microserivce-ci-cd-ecr-repo
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Debug event info
        run: echo "Triggered by workflow run of ${{ github.event.workflow_run.name }}"

      - name: Checkout repo 
        uses: actions/checkout@v3

      - name: Login to ECR 
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin 891062950211.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - name: Build and Push Docker Image
        run: |
          docker build -t 891062950211.dkr.ecr.us-east-1.amazonaws.com/terraform-eks-microservices-ci-cd-ecr-repo:latest ./app
          docker push 891062950211.dkr.ecr.us-east-1.amazonaws.com/terraform-eks-microservices-ci-cd-ecr-repo:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
        
      - name: Deploy to EKS 
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Destroy Infra 
        working-directory: environments/dev
        run: terraform destroy --auto-approve