name: Terraform Infra Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Apply Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Ensure backend bucket exists
        run: |
          aws s3api head-bucket --bucket terraform-eks-microserivce-ci-cd-s3-bucket || \
          aws s3api create-bucket --bucket terraform-eks-microserivce-ci-cd-s3-bucket --region $AWS_REGION

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Format
        working-directory: environments/dev
        run: terraform fmt -recursive

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: environments/dev
        run: terraform apply -auto-approve -input=false
